### PR TITLE
BUGFIX: Fixed incorrectly formed page specific anchor links (fixes #104)

### LINKED ISSUE #104: Issue linking to #id within page #124
e.g. https://docs.silverstripe.org/en/3.3/changelogs/3.2.0/

If you look at the link to "Major Changes" (which points to #major-changes) it links to the current URL without the last URL segment.

### PR DESCRIPTION
**Pull request by UndefinedOffset**
This pull requests fixes the relative anchors on pages like https://docs.silverstripe.org/en/3.3/changelogs/3.2.0/ and resolves issue #104.

### CODE REVIEW

**Comment by UndefinedOffset** [comment]
This also addresses an issue where the heading anchor links would have a duplicate hash added to them if there was one present when the page loaded.

File: code/DocumentationParser.php [hunk 1]
```diff
@@ -482,6 +482,9 @@ public static function rewrite_relative_links($md, $page)
                         $fileBaseLink,
                         $url
                     );
+                } else if (preg_match('/^#/', $url)) {
+                    // for relative links begining with a hash use the current page link
+                    $relativeUrl = Controller::join_links($baselink, $page->getRelativeLink(), '/', $url);
```
Comment (dhensby) [inline code/DocumentationParser.php]: `join_links` adds the `/` between params so the penultimate argument is not needed

Comment (UndefinedOffset) [inline code/DocumentationParser.php]: Right amended :)

**Comment by dhensby** [comment]
THANKS!
